source/blog/urls.py
from django.urls import path
from blog.views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path("", IndexClass.as_view(), name="index"),
    path("new/",FormClass.as_view(), name="post"),
    path("successful/",PostSuccessfulClass.as_view(), name="post_successful"),
    path("list/",PostList.as_view(),name="list"),
    path("list_detail/<int:pk>/",ListDetail.as_view(),name="list_detail"),
    path("login_successful",LoginSuccessfulClass.as_view(),name="login_successful"),
    path("create/",UserCreateClass.as_view(),name='account_create'),
    path("create_successful/",CreateSuccessClass.as_view(),name='create_success'),
    path("login/",LoginClass.as_view(),name='login'),
    path("connect_logout",ConnectLogoutClass.as_view(),name='connect_logout'),
    path("logout/",LogoutClass.as_view(),name='logout'),
    path("logout_success/",LogoutedClass.as_view(),name='logout_successful'),
    path("list_detail/<int:pk>/edit/",ListEditClass.as_view(),name='list_edit'),
    path("edit_successful/",EditSuccessClass.as_view(),name='edit_successful'),
    path("list_detail/<int:pk>/delete",ListDeleteClass.as_view(),name='list_delete'),
    path("delete_successful/",DeleteSuccessClass.as_view(),name='delete_successful'),
    path("user_page/<int:pk>",UserDetailClass.as_view(),name='user_page'),
    path("another_user_page/<int:pk>/<str:username>",Another_UserDetailClass.as_view(),name='another_user_page'),
    path("category_list",CategoryList.as_view(),name='category_list'),
    path("tag_list",TagList.as_view(),name='tag_list'),
    path("category_detail/<int:pk>",CategoryDetail.as_view(),name='category_detail'),
    path("tag_detail/<int:pk>",TagDetail.as_view(),name='tag_detail'),
    path("category_search/<int:pk>",CategoryDetail.as_view(),name='category_search'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/<str:username>', CommentDeleteView.as_view(), name='delete_comment'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/<str:username>',ReplyDeleteView.as_view(), name='delete_reply'),
    path('category_entry/', AddCategoryView.as_view(), name='add_category'),
    path('tag_entry/', AddTagView.as_view(), name='add_tag'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

source/blog/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from .models import Post,CommentPost,ReplyPost,Category,Tag
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model


class CreateForm(UserCreationForm):
    class Meta:
        User = get_user_model()
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class PostList(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('tags','category','content','title','description','username','image')
        widgets = {
        'content':forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'本文の入力'}),
        'description':forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'備考、その他'}),
        'title':forms.Textarea(attrs={'rows':1,'cols':50,'placeholder':'タイトルを255文字以内で入力'}),
        'username':forms.Textarea()
         }

class CommentForm(forms.ModelForm):

    class Meta:
        model = CommentPost
        fields = ('name','content')
        widgets = {
            'name': forms.TextInput(attrs={
                'class':  'form-control',
                'placeholder':'名前',
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder':'本文',
            }),
        }
        labels = {
            'name':'',
            'content':'',
        }
class ReplyForm(forms.ModelForm):

    class Meta:
        model = ReplyPost
        fields = ('name','content')
        widgets = {
            'name': forms.TextInput(attrs={
                'class':  'form-control',
                'placeholder':'名前',
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder':'本文',
            }),
        }
        labels = {
            'name':'',
            'content':'',
        }

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'カテゴリを入力',
            }),

        }
        labels = {
            'name': '',

        }

class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'タグを入力',
            }),

        }
        labels = {
            'name': '',

        }

source/blog/views.py
from django.shortcuts import render
from blog.models import Post,Tag,Category,CommentPost,ReplyPost
from django.views.generic import ListView, CreateView,TemplateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.db.models import Q,Count
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm,CommentForm,ReplyForm,CategoryForm,TagForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostList,CreateForm
from django import forms
from django.http import Http404
from .models import User
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Prefetch
from django.contrib.auth.decorators import login_required



class FormClass(LoginRequiredMixin,CreateView):
    template_name = 'blog/post.html'
    form_class = PostList
    model = User
    success_url = reverse_lazy('blog:post_successful')

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['initial'] = {'username': self.request.user}
        return form_kwargs



class IndexClass(ListView):
    template_name = 'blog/index.html'
    model = Post
    paginate_by = 3


class PostSuccessfulClass(TemplateView):
    template_name = 'blog/post_successful.html'

class PostList(ListView):
    template_name = 'blog/list.html'
    model = Post
    paginate_by = 3
    def get_queryset(self):
        q_word = self.request.GET.get('query')
        print(q_word)

        if q_word:
            object_list = Post.objects.filter(
                title__icontains=q_word)
        else:
            object_list = Post.objects.all()
        return object_list

class ListDetail(DetailView):
    model = Post
    template_name = 'blog/list_detail.html'


class LoginSuccessfulClass(TemplateView):
    template_name = 'blog/login_successful.html'

class UserCreateClass(CreateView):
    form_class = CreateForm
    template_name = 'blog/account_create.html'
    success_url = reverse_lazy('blog:create_success')

class CreateSuccessClass(TemplateView):
    template_name = 'blog/create_success.html'

class LoginClass(LoginView):
    template_name = 'blog/login.html'
    form_class = LoginForm

class ConnectLogoutClass(LoginRequiredMixin, TemplateView):
    template_name = "blog/connect_logout.html"

class LogoutClass(LoginRequiredMixin, LogoutView):
    template_name = "blog/logout.html"

class LogoutedClass(TemplateView):
    template_name = "blog/logout_successful.html"

class ListEditClass(LoginRequiredMixin,UpdateView):
    template_name = 'blog/list_edit.html'
    model = Post
    fields = ['tags', 'category', 'content', 'title', 'description','image']
    success_url = reverse_lazy('blog:edit_successful')

    def get_form(self):
        form = super(ListEditClass, self).get_form()
        form.fields['content'].widget = forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'本文の入力'})
        form.fields['description'].widget = forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'備考、その他'})
        form.fields['title'].widget = forms.Textarea(attrs={'rows':1,'cols':50,'placeholder':'タイトルを255文字以内で入力'})

        return form

class EditSuccessClass(TemplateView):
    template_name = 'blog/edit_successful.html'

class ListDeleteClass(LoginRequiredMixin,DeleteView):
    template_name = 'blog/list_delete.html'
    model = Post
    success_url = reverse_lazy('blog:delete_successful')


class DeleteSuccessClass(TemplateView):
    template_name = 'blog/delete_successful.html'

class UserDetailClass(LoginRequiredMixin,ListView):
    template_name = 'blog/user_page.html'
    model = Post
    def get_queryset(self):
        q_word = self.request.GET.get('query')
        print(q_word)

        if q_word:
            object_list = Post.objects.filter(
                title__icontains=q_word)
        else:
            object_list = Post.objects.all()
        return object_list

class Another_UserDetailClass(ListView):
    template_name = 'blog/another_user_page.html'
    model = Post
    def get_queryset(self):
        q_word = self.request.GET.get('query')
        print(q_word)

        if q_word:
            object_list = Post.objects.filter(
                title__icontains=q_word)
        else:
            object_list = Post.objects.all()
        return object_list

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['username'] = self.kwargs.get('username')
        print(context)
        return context

class CategoryList(ListView):
    template_name = 'blog/category_list.html'
    model = Category

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        print(q_word)
        print(self.queryset)
        if q_word:
            object_list = Category.objects.filter(
                name__icontains=q_word).annotate(
            num_posts=Count('post'))
        else:
            object_list = Category.objects.annotate(
            num_posts=Count('post'))
        return object_list



class TagList(ListView):
    template_name = 'blog/tag_list.html'
    model = Tag

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        print(q_word)
        print(self.queryset)
        if q_word:
            object_list = Tag.objects.filter(
                name__icontains=q_word).annotate(
                num_posts=Count('post'))
        else:
            object_list = Tag.objects.annotate(
                num_posts=Count('post'))
        return object_list



class CategoryDetail(DetailView):
    template_name = 'blog/category_detail.html'
    model = Category



class TagDetail(DetailView):
    template_name = 'blog/tag_detail.html'
    model = Tag


class CommentFormView(CreateView):
    model = CommentPost
    form_class = CommentForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:list_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context



class CommentDeleteView(LoginRequiredMixin,DeleteView):
    template_name = 'blog/delete_comment.html'
    model = CommentPost

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(CommentPost, pk=comment_pk)
        comment.delete()
        return redirect('blog:list_detail',pk=comment.post.pk)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['username'] = self.kwargs.get('username')
        print(context)
        return context


class ReplyFormView(CreateView):
    model = ReplyPost
    form_class = ReplyForm
    template_name = 'blog/reply_form.html'

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        print(self.kwargs)
        reply.comment = get_object_or_404(CommentPost, pk=comment_pk)
        reply.save()
        return redirect('blog:list_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(CommentPost, pk=comment_pk)
        return context

class ReplyDeleteView(LoginRequiredMixin,DeleteView):
    template_name = 'blog/delete_reply.html'
    model = ReplyPost

    def delete(self, request, *args, **kwargs):
        reply_pk = self.kwargs['pk']
        reply = get_object_or_404(ReplyPost, pk=reply_pk)
        reply.delete()
        return redirect('blog:list_detail', pk=reply.comment.post.pk)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['username'] = self.kwargs.get('username')
        print(context)
        return context


class AddCategoryView(LoginRequiredMixin,CreateView):
    template_name = 'blog/add_category.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('blog:category_list')

class AddTagView(LoginRequiredMixin,CreateView):
    template_name = 'blog/add_tag.html'
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('blog:tag_list')

source/blog/templates/blog/include/comments.html
{% for comment in post.comments.all %}

<div class="comment">
  <strong>{{ comment.name }}</strong>・{{ comment.timestamp }}
  <p>{{ comment.content|linebreaksbr }}</p>
  <p>
    <a class="text-primary" href="{% url 'blog:reply_form' comment.pk %}">返信する</a>
    {% if user.is_superuser == 1 %}
    ｜<a class="text-danger" href="{% url 'blog:delete_comment' comment.pk post.username %}">削除する</a>
    {% else %}
    {% if user.username == post.username %}
    ｜<a class="text-danger" href="{% url 'blog:delete_comment' comment.pk post.username %}">削除する</a>
    {% else %}
    {% endif %}
    {% endif %}


  </p>

  {% for reply in comment.reply.all %}

  <div class="reply ml-5">
    <strong>{{ reply.name }}</strong>・{{ reply.timestamp }}
    <p>{{ reply.content|linebreaksbr }}</p>
    <p>
    <a class="text-primary" href="{% url 'blog:reply_form' comment.pk %}">返信する</a>
      {% if user.is_superuser == 1 %}
    ｜<a class="text-danger" href="{% url 'blog:delete_reply' reply.pk post.username %}">削除する</a>
      {% else %}
      {% if user.username == post.username %}
    ｜<a class="text-danger" href="{% url 'blog:delete_reply' reply.pk post.username %}">削除する</a>
    {% else %}
    {% endif %}
    {% endif %}


  </div>

  {% endfor %}
</div>

{% endfor %}

source/blog/templates/blog/include/footer.html
<div class="card text-center">
<div class="bg-image">
    <div class="bg-mask">
  <div class="card-header my-font2">
    <h2>普通の掲示板</h2>

  </div>
   </div>
      </div>
  <div class="card-body">
    <h5 class="card-title">他に作成したもの</h5>
    <p class="card-text">下記ボタンを押すと他のコンテンツへ飛びます。</p>
    <p><a href="{% url 'blog:index' %}"><button type="button" class="btn btn-primary">まだこのコンテンツは未実装です。 </button></a></p>
    </div>
  <div class="card-footer text-muted my-font1">
    <p>Thank you for watching</p>
  </div>
</div>

source/blog/templates/blog/include/header_default.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark my-opacity1 my-font1">
  <a class="navbar-brand" href="{% url 'blog:index' %}">普通の掲示板</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/list">記事一覧へ</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:connect_logout' %}">ログアウト</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:login' %}">ログイン</a>
      </li>

      {% endif %}

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post' %}">記事を投稿する</a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:account_create' %}">アカウント作成</a>
      </li>

      {% endif %}

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:user_page' user.id %}">ユーザーページ</a>
      </li>

      {% else %}

      {% endif %}

    </ul>
    <!--検索窓。-->

    <!--<form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="記事を検索" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
    </form> -->
  </div>
</nav>

source/blog/templates/blog/include/header_search.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark my-opacity1 my-font1">
  <a class="navbar-brand" href="{% url 'blog:index' %}">普通の掲示板</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/list">記事一覧へ</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:connect_logout' %}">ログアウト</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:login' %}">ログイン</a>
      </li>

      {% endif %}

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post' %}">記事を投稿する</a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:account_create' %}">アカウント作成</a>
      </li>

      {% endif %}

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:user_page' user.id %}">ユーザーページ</a>
      </li>

      {% else %}

      {% endif %}

    </ul>
    <!--検索窓。-->

    <form class="form-inline my-2 my-lg-0" action="" method="get">
      <input class="form-control mr-sm-2" name="query" value="{{ request.GET.query }}" placeholder="検索">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
    </form>
  </div>
</nav>

source/blog/templates/blog/include/pagenated.html
<nav>
  <ul class="pagination justify-content-center color">
    <li class="page-item">{% if page_obj.has_previous %}<a class="page-link" href="?page={{ page_obj.previous_page_number }}">前へ{% endif %}</a></li>
   {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
   <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
   {% else %}
   {% if num == 1 %}
    <li class="page-item">
  <a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
   {% else %}
  {% if page_obj.number == num|add:"-1" or page_obj.number == num|add:"1" or page_obj.number == num|add:"-2" or page_obj.number == num|add:"2" %}
   <li class="page-item">
  <a class="page-link" href="?page={{ num }}">{{ num }}</a></li>{% endif %}{% endif %}{% endif %}
  {% endfor %}
    <li class="page-item">{% if page_obj.has_next %}<a class="page-link" href="?page={{ page_obj.next_page_number }}">次へ{% endif %}</a></li>
  </ul>
</nav>