source/blog/urls.py
from django.urls import path
from blog.views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path("", IndexClass.as_view(), name="index"),
    path("new/",FormClass.as_view(), name="post"),
    path("successful/",PostSuccessfulClass.as_view(), name="post_successful"),
    path("list/",PostList.as_view(),name="list"),
    path("list_detail/<int:pk>/",ListDetail.as_view(),name="list_detail"),
    path("login_successful",LoginSuccessfulClass.as_view(),name="login_successful"),
    path("create/",UserCreateClass.as_view(),name='account_create'),
    path("create_successful/",CreateSuccessClass.as_view(),name='create_success'),
    path("login/",LoginClass.as_view(),name='login'),
    path("connect_logout",ConnectLogoutClass.as_view(),name='connect_logout'),
    path("logout/",LogoutClass.as_view(),name='logout'),
    path("logout_success/",LogoutedClass.as_view(),name='logout_successful'),
    path("list_detail/<int:pk>/edit/",ListEditClass.as_view(),name='list_edit'),
    path("edit_successful/",EditSuccessClass.as_view(),name='edit_successful'),
    path("list_detail/<int:pk>/delete",ListDeleteClass.as_view(),name='list_delete'),
    path("delete_successful/",DeleteSuccessClass.as_view(),name='delete_successful'),
    path("user_page/<int:pk>",UserDetailClass.as_view(),name='user_page'),
    path("another_user_page/<int:pk>/<str:username>",Another_UserDetailClass.as_view(),name='another_user_page'),
    path("category_list",CategoryList.as_view(),name='category_list'),
    path("tag_list",TagList.as_view(),name='tag_list'),
    path("category_detail/<int:pk>",CategoryDetail.as_view(),name='category_detail'),
    path("tag_detail/<int:pk>",TagDetail.as_view(),name='tag_detail'),
    path("category_search/<int:pk>",CategoryDetail.as_view(),name='category_search'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/<str:username>', CommentDeleteView.as_view(), name='delete_comment'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/<str:username>',ReplyDeleteView.as_view(), name='delete_reply'),
    path('category_entry/', AddCategoryView.as_view(), name='add_category'),
    path('tag_entry/', AddTagView.as_view(), name='add_tag'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

source/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied
from django.contrib import auth
from django.conf import settings

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    username = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

class CommentPost(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class ReplyPost(models.Model):
    comment = models.ForeignKey(CommentPost,on_delete=models.CASCADE, related_name='reply')
    name = models.CharField(max_length=50)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    'You have multiple authentication backends configured and '
                    'therefore must provide the `backend` argument.'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                'backend must be a dotted import path string (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


# A few helper functions for common logic between User and AnonymousUser.
def _user_get_permissions(user, obj, from_name):
    permissions = set()
    name = 'get_%s_permissions' % from_name
    for backend in auth.get_backends():
        if hasattr(backend, name):
            permissions.update(getattr(backend, name)(user, obj))
    return permissions


def _user_has_perm(user, perm, obj):
    """
    A backend can raise `PermissionDenied` to short-circuit permission checking.
    """
    for backend in auth.get_backends():
        if not hasattr(backend, 'has_perm'):
            continue
        try:
            if backend.has_perm(user, perm, obj):
                return True
        except PermissionDenied:
            return False
    return False


def _user_has_module_perms(user, app_label):
    """
    A backend can raise `PermissionDenied` to short-circuit permission checking.
    """
    for backend in auth.get_backends():
        if not hasattr(backend, 'has_module_perms'):
            continue
        try:
            if backend.has_module_perms(user, app_label):
                return True
        except PermissionDenied:
            return False
    return False


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    #post = models.ManyToManyField(Post, blank=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

source/blog/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from .models import Post,CommentPost,ReplyPost,Category,Tag
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model


class CreateForm(UserCreationForm):
    class Meta:
        User = get_user_model()
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class PostList(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('tags','category','content','title','description','username','image')
        widgets = {
        'content':forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'本文の入力'}),
        'description':forms.Textarea(attrs={'rows':30,'cols':100,'placeholder':'備考、その他'}),
        'title':forms.Textarea(attrs={'rows':1,'cols':50,'placeholder':'タイトルを255文字以内で入力'}),
        'username':forms.Textarea()
         }

class CommentForm(forms.ModelForm):

    class Meta:
        model = CommentPost
        fields = ('name','content')
        widgets = {
            'name': forms.TextInput(attrs={
                'class':  'form-control',
                'placeholder':'名前',
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder':'本文',
            }),
        }
        labels = {
            'name':'',
            'content':'',
        }
class ReplyForm(forms.ModelForm):

    class Meta:
        model = ReplyPost
        fields = ('name','content')
        widgets = {
            'name': forms.TextInput(attrs={
                'class':  'form-control',
                'placeholder':'名前',
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder':'本文',
            }),
        }
        labels = {
            'name':'',
            'content':'',
        }

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'カテゴリを入力',
            }),

        }
        labels = {
            'name': '',

        }

class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'タグを入力',
            }),

        }
        labels = {
            'name': '',

        }

source/blog/templates/blog/add_category.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}
<br><br><br>
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">カテゴリ追加</h1>
      <form action="", method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
          <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </main>
    <aside class="col-md-4">

    </aside>
  </div>
</div>

{% endblock %}

source/blog/templates/blog/add_tag.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}

<br><br><br>
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">タグ追加</h1>
      <form action="", method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
          <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </main>
    <aside class="col-md-4">

    </aside>
  </div>
</div>

{% endblock %}

source/blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block content %}
{% include "blog/include/header_default.html" %}
<br><br><br>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
      <div class="my-font2 padding"><h2>{{object.name}}の投稿一覧</h2></div>
      <ul>
<p>{% for category in object.post_set.all %}</p>
<li class="list-group-item"><a href="{% url 'blog:list_detail' category.id %}">{{ category.title }}</a>
<p>投稿日時:{{category.timestamp}}</p>
  <p><a href="{% url 'blog:list_detail' category.id %}"><button type="button" class="btn btn-primary">記事を読む </button></a></p></li>
<br>
{% endfor %}
      </ul>
    </div>
    <div class="col-lg-2">

    </div>

  </div>
</div>




{% endblock %}

source/blog/templates/blog/comment_form.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>
{% include "blog/include/header_default.html" %}


<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">コメント投稿フォーム</h1>
      <p>To:「{{ post.title }}」</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </main>
    <aside class="col-md-4">

    </aside>
  </div>
</div>


{% endblock %}

source/blog/templates/blog/connect_logout.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_default.html" %}
<br><br><br>
<div class="text-align"><h4>ログアウトしますか？</h4>
<a href="{% url 'blog:logout' %}"><button type="submit" class="btn btn-primary">ログアウト</button></a></div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

source/blog/templates/blog/delete_comment.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_default.html" %}
<br><br><br>
{% if user.is_superuser == 1 or user.username == username %}
    <h1>削除しますか？</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">削除する</button>
    </form>
{% else %}
<h1>投稿ユーザーではない為、削除できません。</h1>
{% endif %}


{% endblock %}

source/blog/templates/blog/delete_reply.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_default.html" %}
<br><br><br>
{% if user.is_superuser == 1 or user.username == username%}
    <h1>削除しますか？</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">削除する</button>
    </form>
{% else %}
<h1>投稿ユーザーではない為、削除できません。</h1>
{% endif %}


{% endblock %}

source/blog/templates/blog/edit_successful.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_default.html" %}
<br><br><br>
<h1>更新が完了しました！</h1>
<a href="{% url 'blog:index' %}"><button type="button" class="btn btn-primary">ホームページへ戻る</button></a>
<a href="{% url 'blog:list' %}"><button type="button" class="btn btn-primary">投稿一覧へ戻る</button></a>
<a href="{% url 'blog:user_page' user.id %}"><button type="button" class="btn btn-primary">ユーザーページへ戻る</button></a>
<br><br>

{% endblock %}

source/blog/templates/blog/list_delete.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_default.html" %}
<br><br><br>
{% if user.username == post.username %}
    <h1>削除しますか？</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">削除する</button>
    </form>
{% else %}
<h1>投稿ユーザーではない為、削除できません。</h1>
{% endif %}

{% endblock %}

source/blog/templates/blog/login.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}
<br><br><br>
<div class="my-font1"><h1>ログイン</h1></div>
<form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">ログイン</button><a href="{% url 'blog:account_create' %}">
        <button type="button" class="btn btn-primary">アカウント作成</button></a>
    <p></p>
    </form>


{% endblock %}

source/blog/templates/blog/login_successful.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}
<br><br><br>
<h2>ログインしました。</h2>
<p><a href="{% url 'blog:index' %}"><button type="button" class="btn btn-primary">ホームページへ戻る</button></a></p>

{% endblock %}

source/blog/templates/blog/logout_successful.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}
<br><br><br>
<div class="text-align"><h4>ログアウトしました。</h4>
<a href="{% url 'blog:index' %}"><button type="button" class="btn btn-primary">ホームページへ戻る</button></a></div>
<br>
{% endblock %}

source/blog/templates/blog/post_successful.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->

{% include "blog/include/header_default.html" %}
<br><br><br>
<h1>投稿が完了しました！</h1>
<form action="", method="post">
    <p><a href="{% url 'blog:index' %}"><button type="button" class="btn btn-primary">トップページへ戻る</button></a></p>
</form>

{% endblock %}

source/blog/templates/blog/user_page.html
{% extends 'base.html' %} <!-- 追加 -->
{% block content %} <!-- 追加 -->
{% include "blog/include/header_search.html" %}
<br><br><br>
<div class="container-fluid">

    <div class="row">
		<div class="col-lg-2">
        </div>
      <div class="col-lg-8">
<div class="my-font2"><h1>{{user.username}}さんの投稿一覧</h1></div>

<ul class="list-group my-font2">
{%  for post in object_list %}
{% if user.username == post.username %}
<li class="list-group-item"><p><a href="{% url 'blog:list_detail' post.id %}">{{post.title}}</a></p>
<p>投稿日時:{{post.timestamp}}</p>
<p><a href="{% url 'blog:list_detail' post.id %}"><button type="button" class="btn btn-primary">記事を読む </button></a></p>
</li>
  <br><br>

{% endif %}
{% endfor %}
</ul>
      </div>
      <div class="col-lg-2">
      </div>
    </div>
<!--{% include "blog/include/pagenated.html" %}-->
</div>
{% endblock %}